repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args:
          - "--count"
          - "--show-source"
          - "--statistics"
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true  # mypy's incremental cache isn't safe for concurrent invocations
        args:
          - "--ignore-missing-imports"
          - "--scripts-are-modules"
      - id: doctest
        name: Run doctest
        entry: python -m doctest
        language: system
        files: .+\.rst|README\.md
      - id: help in doc
        name: Check help in doc
        entry: python crosshair/tools/check_help_in_doc.py --overwrite
        language: system
        pass_filenames: false
        files: .+\.rst|main\.py
      - id: smoke test
        name: Run smoke tests
        entry: env PYTHONHASHSEED=0 python -m pytest -m smoke -n auto --dist worksteal
        language: system
        pass_filenames: false
      - id: pytest
        name: Run all pytest tests
        entry: env PYTHONHASHSEED=0 python -m pytest -n auto --dist worksteal
        language: system
        stages: [manual]
        pass_filenames: false
