name: Build-documentation

on:
  push:
    branches:
      - main
    paths:
      - doc/**

  pull_request:
    paths:
      - doc/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e .[dev]

      - name: Build documentation
        run: |
          cd doc
          sphinx-build source build

      - name: Upload the documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation.zip
          path: doc/build/**
        if: github.event_name == 'push'
